import express from "express";
import { signup, verifyMagicLink, login, getMe, sendMagicLinkForLogin, completeProfile, forgetAccount } from "../controllers/authController.js";
import verifyToken from "../middleware/authMiddleware.js";
const router = express.Router();
router.post("/signup", signup);
router.get("/magic-verify", verifyMagicLink);
router.post("/login", login);
router.post("/magic/send-link", sendMagicLinkForLogin);
router.get("/me", verifyToken, getMe);
router.put("/complete-profile", verifyToken, completeProfile);
router.post("/forget-account", forgetAccount);
export default router;